language: cpp
dist: trusty
env:
  global:
  - secure: oUz4G1tvGWI7W91aJnCA2+JQuYYjdbRxbNpefkdxskZD9tJjT+NjjbZjWjXJxThJNr4t7bPTl6Q3hgtiOeAcRBo0pUKGDlEN3CPcfGIyvdkZSv8ZhdrMBsxJiG/BRBzoh3yVy1Tbkbbe/0mrQhZ0ZbCwLdFZbqDLj+dQRAvlER+kgxwZw8pKrbrEnMt9tK7UHAALkrAV3xFVtDwO1tsVWLgOAiw8FPNnR0QDJfOxok/UmRmRfU5i1Kfpz9KReGGecLRsgYhmxpAm9IiwVecTE3RcUHV3+eVJlwtFEf2dKaga26ApSiDs68NIWqm4RczvGyVk/DZGvQPFRF0LkglwkOeV1BXmja62C3bPpmdvBERdz+tltbtszxURQjtyL+7Egf99x1bwdljlQg1H6MX8QSvraN64ykXr+30quhfV7XWXYOOMKymSjjesbKB5RSL+3pUkzzNrYu2JAQHp9LWT3RMDy4Sd6Xre3krGZ9MCoUFbNvC8c9WO4D9QB8FK+WxlScLagkvHtWd3os0Ory2XPFmOzVxlTjgtRxg4mm6jCB0XFKQwtEcKHnwZQE2hE5BHpfcNlq3RIVy9KiiEvkaKcNbpYJDNuZOBfYIyOCSniI7a3tGcAEuYcHSQVNagtj8afR2UHYFJVgojcrmCMNXQ+M+XBnL5whoQ+YZtttC3xM0=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - gcc-6
    - doxygen
    - valgrind
before_script:
- mkdir -p build
- cd build
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    mkdir -p external/cmake
    pushd external/cmake
    wget https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.sh
    chmod +x cmake-*-Linux-x86_64.sh
    ./cmake-*-Linux-x86_64.sh --exclude-subdir --skip-license
    export PATH="${PWD}/bin:$PATH"
    popd
  else
    if ! brew ls --version cmake &>/dev/null; then brew update; brew install cmake; fi
  fi
- cd ..
matrix:
  include:
  - env: TEST="Xcode 8.3 build, run unittests and publish to codecov"
    os: osx
    cache: ccache
    osx_image: xcode9.1
    script: scripts/travis/build_xcode.sh
    after_success: scripts/travis/publish_to_codecov.sh
  - env: TEST="g++6 build and run unittests"
    os: linux
    cache: ccache
    script: scripts/travis/build_gcc.sh
  - env: TEST="Git check"
    os: linux
    script: scripts/travis/git_check.sh
  - env: TEST="cppcheck analyse"
    os: linux
    script: scripts/travis/cppcheck_analyse.sh
  - env: TEST="AStyle format"
    os: linux
    script: scripts/travis/astyle_format.sh
  - env: TEST="Generate reference guide and publish on git properties-doc"
    os: osx
    osx_image: xcode9.1
    script: scripts/travis/generate_reference_guide.sh
