language: cpp
dist: trusty
env:
  global:
  - secure: cGS+VBwAkSdhm8sEjfC1+3T4fZzxQF03M/klhG5qZ7ic6JJdAo7ygUvva9kCHJplNB3qSf/diDGiN1Nd/nHbhDzmox8laxYYsDKfWkRhcLZoWoKxH+lNuzeS0bdVYvNF0Dl59BjC5Qz1VoYcTkQ5C2JhDbnXk+RTnkaCtZsaaqqVOGsKgGDwL4naJnBS7vT9szNAV4s5+qTE7RjOaeQcQc3JptItBVfvLe++XVXJe+0AT1F9eACgeWX44hwB1m+E0Ow4HsaweiA0cAlL4s2WOhHlXYWC2C4tBMRVxqVpjPulqubH+Ibe+2q3OoJQ4LBi5zW3xUTQdLzpG/m2icWxrBi+onUMrBiBhNx2cnY3Dn++lq3/Oq2Mh2BvNZdWM6hjQckTxDv9T2ye3EereamVbq2BIYYpzhxHKDj7AlPZaiQnzleKD3NCWeTtXU2CbnMI+/5y23NHaW/69PDyCUoICYGAqovllEmjl+hTRmC8wI0keIaV9FFiOKovbSg7lMdMkJ+Ky0NHZT9gMVVXag4f2HUpz9Kf5WzPTtdi2gqvQ9AKh3PoJpmMEi5sUv3K93Fx9qqRyPfkomrETUc29hLFcW9mXQNkSgtU6z823D6cDBHMNzDYu8B9WrOjBF7+ZJvjkgnJHtqlXi5mSrJn7UIGGrsENyh1Kn2P4sex/06c0OY=
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - gcc-6
    - doxygen
    - valgrind
before_script:
- mkdir -p build
- cd build
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    mkdir -p external/cmake
    pushd external/cmake
    wget https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.sh
    chmod +x cmake-*-Linux-x86_64.sh
    ./cmake-*-Linux-x86_64.sh --exclude-subdir --skip-license
    export PATH="${PWD}/bin:$PATH"
    popd
  else
    if ! brew ls --version cmake &>/dev/null; then brew update; brew install cmake; fi
  fi
- cd ..
matrix:
  include:
  - env: TEST="Xcode 8.3 build, run unittests and publish to codecov"
    os: osx
    cache: ccache
    osx_image: xcode9.1
    script: scripts/travis/build_xcode.sh
    after_success: scripts/travis/publish_to_codecov.sh
  - env: TEST="g++6 build and run unittests"
    os: linux
    cache: ccache
    script: scripts/travis/build_gcc.sh
  - env: TEST="Git check"
    os: linux
    script: scripts/travis/git_check.sh
  - env: TEST="cppcheck analyse"
    os: linux
    script: scripts/travis/cppcheck_analyse.sh
  - env: TEST="AStyle format"
    os: linux
    script: scripts/travis/astyle_format.sh
  - env: TEST="Generate reference guide and publish on git properties-doc"
    os: osx
    osx_image: xcode9.1
    script: scripts/travis/generate_reference_guide.sh
